[tool.black]
exclude = '''
    /(
        \.git
        | \.hg
        | \.mypy_cache
        | \.tox
        | \.venv
        | \._build
        | \.back.out
        | \.build
        | \.dist
        | blib2to3
        | tests/data
    )/
'''
include = '\.pyi?$'
line-length = 119

[tool.isort]
combine_as_imports = true
ensure_newline_before_comments = true
force_alphabetical_sort_within_sections = true
force_grid_wrap = 0
include_trailing_comma = true
line_length = 119
lines_between_sections = 1
multi_line_output = 3
profile = "black"
skip = [
    ".coverage",
    ".dockerignore",
    ".env",
    ".github",
    ".gitignore",
    ".html",
    ".md",
    ".python-version",
    ".rst",
    ".xml"
]
skip_glob = ["migrations/**"]
src_paths = ["app/", "tests/"]
use_parentheses = true

[tool.mypy]
check_untyped_defs = true
color_output = true
error_summary = true
ignore_missing_imports = true
pretty = true
python_version = "3.10"
strict_optional = false
warn_no_return = true
warn_return_any = true

[tool.pytest.ini_options]
testpaths = "tests"
filterwarnings = "error"
addopts = '''
    --strict-markers
    --tb=short
    --cov=app
    --cov=tests
    --cov-branch
    --cov-report=term-missing
    --cov-report=html:coverage/cov_html
    --cov-report=xml:coverage/cov.xml
    --no-cov-on-fail
    --cov-fail-under=1.5
    --numprocesses=auto
    --asyncio-mode=auto
'''

[tool.coverage.run]
omit = ["app/db/database.py"]

[tool.pylint.master]
max-line-length = 119
ignore-paths = ["./tests/"]

[tool.pylint.messages_control]
disable = [
    "C0103", "C0114", "C0116", "C0115", "C0411", "C0415",
    "E1101", "E1111", "E0213", "E0401", "E0611", "E1121",
    "R0801", "R0903",
    "W0106", "W0143", "W0611", "W0613", "W0621", "W0622", "W1203",
    "E0211", "E1123" # > TOBE DELETED FOR DEPLOYMENT
]